---
title: "brms-tutorial"
author: "Jimmy Erkens"
date: "2023-09-04"
output: html_document
---

# Annotated trial on brms

## Libraries and data initializations

```{r}
# libraries
library(brms)
library(effects) # saw some guy online talking abt this package idk
# following procedure from brms: An R Package for Bayesian Multilevel Models
# Using Stan, Bürkner
head(kidney, 10)
# nothing to initialize here super ezpz
```

## Model fitting

```{r}
fit1 <- brm(formula = 
            time | cens(censored) ~ age * sex + disease + (1 + age|patient),
# "In the present example, only one group-level term is specified in which 
# 1 + age are the coefficients varying with the grouping factor patient. 
# This implies that the intercept of the model as well as the effect of age 
# is supposed to vary between patients."
            data = kidney, family = lognormal(), # family = response likelihood
            prior = c(set_prior("normal(0, 5)", class = "b"), # beta variables
                      set_prior("cauchy(0,2)", class = "sd"),
                      set_prior("lkj(2)", class = "cor")), warmup = 10000,
            iter = 20000, chains = 4, control = list(adapt_delta = 0.95))
# we used 10000 burnin and 20000 total iters in undergrad, paper uses 1000/2000
# idk what's up w that

# 4 chains is a good default
# significantly easier to manage than rjags
# HMC algorithm also may be a bit better for analyzing my things
# than Gibbs sampling idk
```

## Model analysis

```{r}
summary(fit1, waic = T) # waic is bayesian adjusted AIC 
plot(fit1) # took forever to plot so weird, be aware of this
```

